### ISSUE TITLE
Override probot/stale defaults, if necessary

### ISSUE THREAD

**Issue by kytrinyx** [exercism/xceylon#32]
Per the discussion in https://github.com/exercism/discussions/issues/128 we
will be installing the probot/stale integration on the Exercism organization on
April 10th, 2017.

By default, probot will comment on issues that are older than 60 days, warning
that they are stale. If there is no movement in 7 days, the bot will close the issue.
By default, anything with the labels `security` or `pinned` will not be closed by
probot.

If you wish to override these settings, create a .github/stale.yml file as described
in https://github.com/probot/stale#usage, and make sure that it is merged
before April 10th.

If the defaults are fine for this repository, then there is nothing further to do.
You may close this issue.

**Comment by petertseng** [comment]
We'll try out the defaults. I pinned the issues that should stay.

**Comment by kytrinyx** [comment]
I made a mistake.

This was not explicitly documented in the README, but probot/stale **requires the presence of a .github/stale.yml** file.

If you want the default behavior, you need to add an empty .github/stale.yml file to this repo, otherwise the bot will not be active.

**Comment by petertseng** [comment]
Going to relieve maintainers of this track from the duty of putting the pinned label on issues, then, by not creating .github/stale.yml

**Comment by petertseng** [comment]
I made my decision unilaterally based on a gut feeling, but now I can back it up with data.

I used https://gist.github.com/petertseng/04edd07d4b35cda2cbc1d8142b6fcc13 to get a rough idea of the issues that would have been closed by this integration. (Limitations: It doesn't look at pull requests, and it may have false positives for issues that are edited after they are closed)

In this track's history, 6/8 issues went stale (I deliberately do not include a # in front of each since I don't mean to reference those issues from this one):

```
 15 Test names pollute student namespace
  7 Verify contents and format of track documentation
  4 Update config.json to match new specification
  3 Consider consistency for the exercises
  2 Test the tests
  1 Launch Checklist
```

Of these, 1, 2, 3, 4, and 7 all have a clear call to action, and 15 is a documented problem that should not be forgotten about. So I wouldn't recommend that those issues be closed no matter how stale they get. So in 6 cases the bot would have caused extra work for the maintainers of this track and in no case (yet!) can the bot save work.

So, I stand by the earlier decision.

**Comment by kytrinyx** [comment]
Agreed. It looks like this repo doesn't have a problem with stale issues. Thanks for taking a serious look at it, @petertseng
