### ISSUE TITLE
Investigate track health and status of the track

### ISSUE THREAD

**Issue by kytrinyx** [exercism/xceylon#6]
I've used Sarah Sharp's [FOSS Heartbeat](https://github.com/sarahsharp/foss-heartbeat) project to generate stats for each of the language track repositories, as well as the x-common repository.

The Exercism heartbeat data is published here: https://exercism.github.io/heartbeat/

When looking at the data, please disregard any activity from me (`kytrinyx`), as I would like to get the language tracks to a point where they are entirely maintained by the community.

Please take a look at the heartbeat data for this track, and answer the following questions:

* To what degree is the track maintained?
* Who (if anyone) is merging pull requests?
* Who (if anyone) is reviewing pull requests?
* Is there someone who is not merging pull requests, but who comments on issues and pull requests, has thoughtful feedback, and is generally helpful? If so, maybe we can invite them to be a maintainer on the track.

I've made up the following scale:

* **ORPHANED** - Nobody (other than me) has merged anything in the past year.
* **ENDANGERED** - Somewhere between ORPHANED and AT RISK.
* **AT RISK** - Two people (other than me) are actively discussing issues and reviewing and merging pull requests.
* **MAINTAINED** - Three or more people (other than me) are actively discussing issues and reviewing and merging pull requests.

It would also be useful to know if there a lot of activity on the track, or just the occasional issue or comment.

Please report the current status of the track, including your best guess on the above scale, back to the top-level issue in the discussions repository: https://github.com/exercism/discussions/issues/97

**Comment by kytrinyx** [comment]
No data available for this track. It is inactive.

**Comment by petertseng** [comment]
Hello. I have taken the Ceylon track under my wing and have done some work on it the past few days, out of my interest in the language.

My primary concern for myself is that I am very much a beginner in Ceylon, so the danger is that I will write unidiomatic code or create unusual project structures. I have tried to document my decisions so that if a more experienced Ceylon user comes along later, the rationale behind my decisions will be understandable and that informed decisions can be made on whether to change them.

I can't promise "I will definitely get this track launched", but I will definitely work to satisfy my curiosity on Ceylon, and I hope the work can become useful to someone.

**Comment by kytrinyx** [comment]
I've invited @chochos to the team. He's a member of the Ceylon core team, and is willing to provide feedback on the pull requests.

**Comment by chochos** [comment]
@petertseng if you have any doubts you can contact the team directly at our gitter page https://gitter.im/ceylon/user
